### ISSUE TITLE
Getting crash org.koin.core.scope.Scope.throwDefinitionNotFound

### ISSUE THREAD

**Issue by nikhilk1993** [refiner-io/mobile-sdk-react-native#4]
version :"refiner-react-native": "0.0.8",

Crash details:
Scope.kt line 305
org.koin.core.scope.Scope.throwDefinitionNotFound

Crash stack trace:
`Caused by ri.d: |- No definition found for class:'io.refiner.ui.SurveyViewModel'. Check your definitions!
       at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:305)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:275)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
       at org.koin.core.scope.Scope.get(Scope.kt:205)
       at io.refiner.ui.SurveyFragment$k.invoke(SourceFile:3)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.refiner.ui.SurveyFragment.getViewModel(SourceFile:1)
       at io.refiner.ui.SurveyFragment.onCreate(SourceFile:8)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7923)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3332)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by chezmo** [comment]
Thanks @nikhilk1993 for bringing this to our attention! 

Does this issue occur on all platforms and OS versions? Also, would it be possible to see some the source code where this gets thrown? If you want, you can send us additional information to contact [at] refiner.io. 

Thank you!

**Comment by chezmo** [comment]
Hi @nikhilk1993 ! Unfortunately we weren't able to reproduce the issue. It seems like the SDK was not loaded correctly though. Is this still happening after clearing all caches and rebuilding the app?

**Comment by charles-kassab** [comment]
Hi,
I got the same crash between Android 10 and 12, no one running on background, Firebase stack trace:
```
Caused by org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'io.refiner.ui.RefinerSurveyViewModel'. Check your definitions!
       at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:305)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:275)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
       at org.koin.core.scope.Scope.get(Scope.kt:205)
       at io.refiner.ui.RefinerSurveyFragment$k.invoke(SourceFile:3)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.refiner.ui.RefinerSurveyFragment.getViewModel(SourceFile:1)
       at io.refiner.ui.RefinerSurveyFragment.onCreate(SourceFile:8)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
       at io.refiner.ui.RefinerSurveyActivity.onCreate(SourceFile:1)
       at android.app.Activity.performCreate(Activity.java:8142)
       at android.app.Activity.performCreate(Activity.java:8114)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3549)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3748)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

Checked if user has enough memory and storage space.
Checked SDK implementation.
ProGuard - minify disabled.

Packages version:
"react-native": "0.70.0"
"react": "18.1.0"
"refiner-react-native": "^1.1.0"

**Comment by chezmo** [comment]
Hi @charles-kassab, we've released a new version of our SDK which might fix this issue. Can you please check if this is still happening with the latest version?

**Comment by tekinalper** [comment]
Closing the issue due to inactivity. Please try latest version published.
